phrase = "Dont't panic!"
plist = list(phrase)
print(phrase)
print(plist)
for i in range(4):
    plist.pop()
plist.pop(0)
plist.remove("'")
plist.remove(" ")
plist.remove("t")
plist.pop()
plist.insert(3, "a")
plist.insert(2, " ")
new_phrase = "".join(plist)
print(plist)
print(new_phrase)